import { test, beforeEach, expect } from "vitest";
import fs from "fs";
import path from "path";
import { cp, rm, mkdir } from "shelljs";
import { spawn } from "first-base";
import { binDir, rootDir } from "./_utils";

// Generated by running this in `qjs --bignum`: require("quickjs:bytecode").fromFile("./tests/fixtures/log-four.js")
const bytecode = Buffer.from([
  3, 3, 14, 99, 111, 110, 115, 111, 108, 101, 6, 108, 111, 103, 56, 46, 47, 116,
  101, 115, 116, 115, 47, 102, 105, 120, 116, 117, 114, 101, 115, 47, 108, 111,
  103, 45, 102, 111, 117, 114, 46, 106, 115, 12, 0, 6, 0, 162, 1, 0, 1, 0, 4, 0,
  0, 18, 1, 164, 1, 0, 0, 0, 56, 228, 0, 0, 0, 66, 229, 0, 0, 0, 185, 185, 158,
  36, 1, 0, 207, 40, 204, 3, 1, 0,
]);

const workdir = rootDir("build/tests/qjsbootstrap-bytecode");

beforeEach(() => {
  rm("-rf", workdir);
  mkdir("-p", workdir);
});

test("qjsbootstrap-bytecode - can execute bytecode", async () => {
  const prog = path.join(workdir, "myprog");
  cp(binDir("qjsbootstrap-bytecode"), prog);
  fs.appendFileSync(prog, bytecode);

  const run2 = spawn(prog, { argv0: "myprog" });
  await run2.completion;
  expect(run2.result).toMatchInlineSnapshot(`
    {
      "code": 0,
      "error": null,
      "stderr": "",
      "stdout": "4
    ",
    }
  `);
});
