/*
 * Shift_JIS table generator
 *
 * Reads the WHATWG index-jis0208.txt file and generates a C header
 * containing the JIS X 0208 lookup table.
 *
 * Usage: shiftjis_gen <input_dir> <output_file>
 *
 * The input_dir should contain index-jis0208.txt (from
 * https://encoding.spec.whatwg.org/index-jis0208.txt).
 *
 * The table size is derived from the maximum pointer value found in the
 * input file, so no hardcoded size is needed.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
    FILE *fin, *fout;
    char line[512];
    char inpath[1024];
    int count = 0;
    int max_pointer = -1;
    int table_size;
    uint16_t *table;

    if (argc != 3) {
        fprintf(stderr, "Usage: %s <input_dir> <output_file>\n", argv[0]);
        return 1;
    }

    snprintf(inpath, sizeof(inpath), "%s/index-jis0208.txt", argv[1]);

    /* First pass: find the maximum pointer value */
    fin = fopen(inpath, "r");
    if (!fin) {
        fprintf(stderr, "Cannot open %s\n", inpath);
        return 1;
    }

    while (fgets(line, sizeof(line), fin)) {
        int pointer;
        unsigned int codepoint;

        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r')
            continue;

        if (sscanf(line, " %d\t0x%X", &pointer, &codepoint) == 2) {
            if (pointer > max_pointer)
                max_pointer = pointer;
        }
    }
    fclose(fin);

    if (max_pointer < 0) {
        fprintf(stderr, "shiftjis_gen: no entries found in %s\n", inpath);
        return 1;
    }

    table_size = max_pointer + 1;
    table = calloc(table_size, sizeof(uint16_t));
    if (!table) {
        fprintf(stderr, "shiftjis_gen: out of memory (table_size=%d)\n", table_size);
        return 1;
    }

    /* Second pass: populate the table */
    fin = fopen(inpath, "r");
    if (!fin) {
        fprintf(stderr, "Cannot open %s\n", inpath);
        free(table);
        return 1;
    }

    while (fgets(line, sizeof(line), fin)) {
        int pointer;
        unsigned int codepoint;

        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r')
            continue;

        if (sscanf(line, " %d\t0x%X", &pointer, &codepoint) == 2) {
            if (pointer >= 0 && pointer < table_size) {
                table[pointer] = (uint16_t)codepoint;
                count++;
            }
        }
    }
    fclose(fin);

    fprintf(stderr, "shiftjis_gen: read %d entries (max pointer %d) from index-jis0208.txt\n",
            count, max_pointer);

    fout = fopen(argv[2], "w");
    if (!fout) {
        fprintf(stderr, "Cannot open %s for writing\n", argv[2]);
        free(table);
        return 1;
    }

    fprintf(fout, "/* Auto-generated by shiftjis_gen from index-jis0208.txt. Do not edit. */\n\n");
    fprintf(fout, "#define JIS0208_TABLE_SIZE %d\n\n", table_size);
    fprintf(fout, "static const uint16_t jis0208_table[JIS0208_TABLE_SIZE] = {\n");

    for (int i = 0; i < table_size; i++) {
        if (i % 16 == 0)
            fprintf(fout, "    ");
        fprintf(fout, "0x%04X,", table[i]);
        if (i % 16 == 15 || i == table_size - 1)
            fprintf(fout, "\n");
        else
            fprintf(fout, " ");
    }

    fprintf(fout, "};\n");
    fclose(fout);
    free(table);

    return 0;
}
