# Dockerfile for: suchipi/quickjs-build:windows-from-linux
#
# This dockerfile creates an image with an environment suitable for compiling
# the "windows-from-linux" variant in, via `make`.

FROM suchipi/quickjs-build:linux-from-linux

USER root

RUN apt-get update && \
  apt-get install -y \
    gcc-mingw-w64-x86-64

USER user

ENV VARIANT windows-from-linux
