/*
 * QuickJS bootstrap
 *
 * Built by Lily Skye, using some code generated by qjsc.
 *
 * Copyright (c) 2022-2023 Lily Skye
 * Copyright (c) 2017-2021 Fabrice Bellard
 * Copyright (c) 2017-2021 Charlie Gordon
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#ifdef __COSMO__
__static_yoink("blink_linux_aarch64");
__static_yoink("blink_xnu_aarch64");
#endif

#include <stdio.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>
#include "execpath.h"
#include "cutils.h"
#include "quickjs-full-init.h"
#include "zip.h"

static JSContext *JS_NewCustomContext(JSRuntime *rt)
{
  JSContext *ctx = JS_NewContextRaw(rt);
  if (!ctx)
    return NULL;
  JS_AddIntrinsicBaseObjects(ctx);
  JS_AddIntrinsicDate(ctx);
  JS_AddIntrinsicEval(ctx);
  JS_AddIntrinsicStringNormalize(ctx);
  JS_AddIntrinsicRegExp(ctx);
  JS_AddIntrinsicJSON(ctx);
  JS_AddIntrinsicProxy(ctx);
  JS_AddIntrinsicMapSet(ctx);
  JS_AddIntrinsicTypedArrays(ctx);
  JS_AddIntrinsicPromise(ctx);
  JS_AddIntrinsicBigInt(ctx);
  JS_AddIntrinsicBigFloat(ctx);
  JS_AddIntrinsicBigDecimal(ctx);
  JS_AddIntrinsicOperators(ctx);
  JS_EnableBignumExt(ctx, TRUE);

  quickjs_full_init(ctx);

  return ctx;
}

static int eval_buf(JSContext *ctx, const void *buf, int buf_len,
                    const char *filename, int eval_flags)
{
  JSValue val;
  int ret;

  if ((eval_flags & JS_EVAL_TYPE_MASK) == JS_EVAL_TYPE_MODULE) {
    /* for the modules, we compile then run to be able to set
        import.meta */
    val = JS_Eval(ctx, buf, buf_len, filename,
                  eval_flags | JS_EVAL_FLAG_COMPILE_ONLY);
    if (!JS_IsException(val)) {
        js_module_set_import_meta(ctx, val, TRUE);
        val = JS_EvalFunction(ctx, val);
    }
  } else {
    val = JS_Eval(ctx, buf, buf_len, filename, eval_flags);
  }

  if (JS_IsException(val)) {
    js_std_dump_error(ctx);
    ret = 1;
  } else {
    ret = 0;
  }

  JS_FreeValue(ctx, val);
  return ret;
}

typedef enum {
  CODE_KIND_UNKNOWN,
  CODE_KIND_UTF8,
  CODE_KIND_BYTECODE,
} CODE_KIND;

typedef struct code_from_zip_result_t {
  int status;
  CODE_KIND kind;
} code_from_zip_result_t;

#define INSTRUCTIONS "append a zip file to the end of this binary containing either a file named 'main.bin' containing quickjs bytecode or a file named 'main.js' containing UTF-8 encoded JavaScript source code.\n"

static code_from_zip_result_t read_code_from_zip(char *argv0, size_t* appended_code_len, void **appended_code)
{
  char *self_binary_path;
  char execpath_error[2048];
  code_from_zip_result_t ret = { 0, CODE_KIND_UNKNOWN };
  struct zip_t *zip = NULL;

  self_binary_path = execpath(argv0, NULL, (char *)&execpath_error);
  if (self_binary_path == NULL) {
    printf("failed to find location of self executable: %s\n", execpath_error);
    ret.status = 1;
    return ret;
  }

  {
    int level;
    for (level = 0; level < 10; level++) {
      zip = zip_open(self_binary_path, level, 'r');
      if (zip != NULL) {
        break;
      }
    }
  }
  if (zip == NULL) {
    printf("failed to open %s as zip file\n" INSTRUCTIONS, self_binary_path);
    ret.status = 1;
    free(self_binary_path);
    return ret;
  }
  {
    int main_bin_result = zip_entry_open(zip, "main.bin");
    if (main_bin_result == 0) {
      ret.kind = CODE_KIND_BYTECODE;
    } else {
      int main_js_result = zip_entry_open(zip, "main.js");
      if (main_js_result == 0) {
        ret.kind = CODE_KIND_UTF8;
      } else {
        printf("failed to open %s as zip file\n" INSTRUCTIONS, self_binary_path);
        ret.status = 1;
        zip_close(zip);
        free(self_binary_path);
        return ret;
      }
    }

    {
      ssize_t entry_read_result = zip_entry_read(zip, appended_code, appended_code_len);
      if (entry_read_result < 0) {
        const char *entry_name;
        if (ret.kind == CODE_KIND_BYTECODE) {
          entry_name = "main.bin";
        } else {
          entry_name = "main.js";
        }
        printf("failed to read '%s' in zip '%s': %s\n" INSTRUCTIONS, entry_name, self_binary_path, zip_strerror(entry_read_result));
        ret.status = 1;
        zip_entry_close(zip);
        zip_close(zip);
        free(self_binary_path);
        return ret;
      }
    }
    zip_entry_close(zip);
  }
  zip_close(zip);

  free(self_binary_path);
  return ret;
}

int main(int argc, char **argv)
{
  JSRuntime *rt;
  JSContext *ctx;
  code_from_zip_result_t zip_result;
  size_t appended_code_len = 0;
  void *appended_code = NULL;

  zip_result = read_code_from_zip(argv[0], &appended_code_len, &appended_code);
  if (zip_result.status != 0 || zip_result.kind == CODE_KIND_UNKNOWN) {
    return 1;
  }

  rt = JS_NewRuntime();
  js_std_set_worker_new_context_func(JS_NewCustomContext);
  js_std_init_handlers(rt);
  JS_SetMaxStackSize(rt, 8000000);
  JS_SetModuleLoaderFunc(rt, js_module_normalize_name, js_module_loader, NULL);
  JS_SetCanBlock(rt, TRUE);
  ctx = JS_NewCustomContext(rt);
  js_std_add_helpers(ctx, argc, argv);

  if (appended_code_len != 0) {
    if (zip_result.kind == CODE_KIND_BYTECODE) {
      js_std_eval_binary(ctx, appended_code, appended_code_len, 0);
    } else {
      if (eval_buf(ctx, appended_code, appended_code_len, "main.js", JS_EVAL_TYPE_MODULE)) {
        return 1;
      }
    }
  }

  js_std_loop(ctx);
  JS_FreeContext(ctx);
  JS_FreeRuntime(rt);
  return 0;
}
