/*
 * QuickJS Core Run - quickjs-run but with only the "core" parts of quickjs
 *
 * Built by Lily Skye, using some code generated by qjsc.
 *
 * Copyright (c) 2022-2023 Lily Skye
 * Copyright (c) 2017-2021 Fabrice Bellard
 * Copyright (c) 2017-2021 Charlie Gordon
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#ifdef __COSMO__
__static_yoink("blink_linux_aarch64");
__static_yoink("blink_xnu_aarch64");
#endif

#include <stdio.h>
#include <string.h>
#include "quickjs.h"
#include "quickjs-modulesys.h"
#include "cutils.h"

static JSContext *JS_NewCustomContext(JSRuntime *rt)
{
  JSContext *ctx = JS_NewContextRaw(rt);
  if (!ctx) {
    return NULL;
  }

  JS_AddIntrinsicBaseObjects(ctx);
  JS_AddIntrinsicDate(ctx);
  JS_AddIntrinsicEval(ctx);
  JS_AddIntrinsicStringNormalize(ctx);
  JS_AddIntrinsicRegExp(ctx);
  JS_AddIntrinsicJSON(ctx);
  JS_AddIntrinsicProxy(ctx);
  JS_AddIntrinsicMapSet(ctx);
  JS_AddIntrinsicTypedArrays(ctx);
  JS_AddIntrinsicPromise(ctx);
  JS_AddIntrinsicBigInt(ctx);
  JS_AddIntrinsicBigFloat(ctx);
  JS_AddIntrinsicBigDecimal(ctx);
  JS_AddIntrinsicOperators(ctx);
  JS_EnableBignumExt(ctx, TRUE);

  return ctx;
}


static JSValue js_print(JSContext *ctx, JSValueConst this_val,
                        int argc, JSValueConst *argv, int magic)
{
    int i;
    const char *str;
    size_t len;
    FILE *out;

    if (magic == 1) {
        out = stdout;
    } else if (magic == 2) {
        out = stderr;
    } else {
        return JS_ThrowInternalError(ctx, "js_print called with incorrect 'magic' value. This is a bug in quickjs-libc.");
    }

    for(i = 0; i < argc; i++) {
        if (i != 0) {
            putc(' ', out);
        }
        str = JS_ToCStringLen(ctx, &len, argv[i]);
        if (!str)
            return JS_EXCEPTION;
        fwrite(str, 1, len, out);
        JS_FreeCString(ctx, str);
    }
    putc('\n', out);
    return JS_UNDEFINED;
}

void js_std_add_console(JSContext *ctx)
{
    JSValue global_obj, console;

    global_obj = JS_GetGlobalObject(ctx);

    console = JS_NewObject(ctx);
    JS_SetPropertyStr(ctx, console, "log",
                      JS_NewCFunctionMagic(ctx, js_print, "log", 1,
                                           JS_CFUNC_generic_magic, 1));
    JS_SetPropertyStr(ctx, console, "info",
                      JS_NewCFunctionMagic(ctx, js_print, "info", 1,
                                           JS_CFUNC_generic_magic, 1));
    JS_SetPropertyStr(ctx, console, "warn",
                      JS_NewCFunctionMagic(ctx, js_print, "warn", 1,
                                           JS_CFUNC_generic_magic, 2));
    JS_SetPropertyStr(ctx, console, "error",
                      JS_NewCFunctionMagic(ctx, js_print, "error", 1,
                                           JS_CFUNC_generic_magic, 2));
    JS_SetPropertyStr(ctx, global_obj, "console", console);

    JS_FreeValue(ctx, global_obj);
}

void js_std_add_print(JSContext *ctx)
{
    JSValue global_obj = JS_GetGlobalObject(ctx);

    JS_SetPropertyStr(ctx, global_obj, "print",
                      JS_NewCFunctionMagic(ctx, js_print, "print", 1,
                                           JS_CFUNC_generic_magic, 1));

    JS_FreeValue(ctx, global_obj);
}


int main(int argc, char **argv)
{
  int status_code;
  JSRuntime *rt;
  JSContext *ctx;
  const char *filename;

  if (argc < 2) {
    printf("You must pass a parameter to this binary: The file to run.\n");
    return 2;
  }

  filename = argv[1];

  rt = JS_NewRuntime();
  JS_SetMaxStackSize(rt, 8000000);
  QJMS_InitState(rt);
  JS_SetCanBlock(rt, TRUE);
  ctx = JS_NewCustomContext(rt);
  QJMS_InitContext(ctx);

  js_std_add_console(ctx);
  js_std_add_print(ctx);

  status_code = 0;

  if (QJMS_EvalFile(ctx, filename, -1)) {
    status_code = 1;
  }

  QJMS_FreeState(rt);
  JS_FreeContext(ctx);
  JS_FreeRuntime(rt);
  return status_code;
}
