build(
  builddir("libregexp.host.o"),
  "compile_host_c_object",
  [rel("libregexp.c")],
  [builddir("libunicode.host.o")]
);
build(
  builddir("libregexp.target.o"),
  "compile_target_c_object",
  [rel("libregexp.c")],
  [builddir("libunicode.target.o")]
);
