name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test (Ubuntu)
        run: meta/ci.sh

  build-and-test-macos:
    # Note: 14 image uses M1 (arm) processor
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test (macOS)
        run: meta/ci.sh
